/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConnectionInfo.java
 *
 * Created on 19.4.2011, 21:24:50
 */
package cz.cvut.fel.mvod.gui.settings.panels;

import cz.cvut.fel.mvod.global.GlobalSettingsAndNotifier;
import cz.cvut.fel.mvod.global.Notifiable;
import javax.swing.JOptionPane;

/**
 *
 * @author Murko
 */
public class ConnectionInfo extends javax.swing.JPanel implements Notifiable {

    /** Creates new form ConnectionInfo */
    public ConnectionInfo() {
        initComponents();
        GlobalSettingsAndNotifier.singleton.addListener(this);
        notifyOfChange();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        portNumber = new javax.swing.JTextField();
        SSLPortNumber = new javax.swing.JTextField();
        serverName = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Nastavenia pripojenia");

        jLabel2.setText("Cislo portu");

        jLabel3.setText("Cispo zabezpeceneho portu");

        jLabel4.setText("Meno servera");

        portNumber.setText(GlobalSettingsAndNotifier.singleton.getSetting("HTTP_PORT"));
        portNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portNumberActionPerformed(evt);
            }
        });
        portNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                portNumberFocusLost(evt);
            }
        });

        SSLPortNumber.setText(GlobalSettingsAndNotifier.singleton.getSetting("SSL_PORT"));
        SSLPortNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SSLPortNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SSLPortNumberFocusLost(evt);
            }
        });

        serverName.setText(GlobalSettingsAndNotifier.singleton.getSetting("SERVER_NAME"));
        serverName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverNameActionPerformed(evt);
            }
        });
        serverName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                serverNameFocusLost(evt);
            }
        });

        jCheckBox1.setText("Povoliť automatické objavovanie");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serverName, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(SSLPortNumber)
                            .addComponent(portNumber))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(portNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SSLPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(serverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void portNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portNumberActionPerformed

    private void serverNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverNameActionPerformed

    private void portNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_portNumberFocusLost
        portChange("HTTP_PORT", portNumber.getText());
    }//GEN-LAST:event_portNumberFocusLost

    private void SSLPortNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SSLPortNumberFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_SSLPortNumberFocusGained

    private void SSLPortNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SSLPortNumberFocusLost
        portChange("SSL_PORT", SSLPortNumber.getText());
    }//GEN-LAST:event_SSLPortNumberFocusLost

    private void serverNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_serverNameFocusLost
        if (!serverName.getText().equals("")) {
            GlobalSettingsAndNotifier.singleton.modifySettings("SERVER_NAME", serverName.getText());
        }
    }//GEN-LAST:event_serverNameFocusLost

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
        GlobalSettingsAndNotifier.singleton.modifySettings("allowBeacon", jCheckBox1.isSelected()?"true":"false",true);
    }//GEN-LAST:event_jCheckBox1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SSLPortNumber;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField portNumber;
    private javax.swing.JTextField serverName;
    // End of variables declaration//GEN-END:variables

    private void portChange(String type, String number) {
        try {
            int port = Integer.parseInt(number);
            if (port < 0 || port > 65555) {
                throw new NumberFormatException();
            }
            GlobalSettingsAndNotifier.singleton.modifySettings(type, port + "",true);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Prosim zadajte cislo od 0 do 65555",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

        }

    }

    @Override
    public void notifyOfChange() {
        jCheckBox1.setSelected(GlobalSettingsAndNotifier.singleton.getSetting("allowbeacon").equalsIgnoreCase("true")?true:false);
    }
}
